spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username:root
    password:1234565
    url:jdbc:mysql://192.168.0.113/prodect/characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql:true

